name: Test docusaurus deployment

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node and install dependencies
        run: |
            npm config set prefix=$(pwd)/.npm-global
            npm config set cache=$(pwd)/.npm-cache
            npm ci
            working-directory: ./website

      - name: Build website
        working-directory: ./website
        run: npm run build